# Generated by Django 5.1.15 on 2026-02-23 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_prefix', models.CharField(blank=True, default='', max_length=8)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('units_consumed', models.IntegerField(default=0)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('query_ms', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usage record',
                'verbose_name_plural': 'usage records',
                'db_table': 'tickerflow_usage_ledger',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='idx_usage_user_ts'), models.Index(fields=['endpoint', '-timestamp'], name='idx_usage_endpoint_ts')],
            },
        ),
    ]
