apiVersion: v1
kind: ConfigMap
metadata:
  name: tickerflow-config
  namespace: tickerflow
  labels:
    app: tickerflow
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  DB_HOST: "192.168.1.40"
  DB_PORT: "5432"
  DB_NAME: "stock-dumps"
  DB_USER: "sd_admin"
  DB_CONN_MAX_AGE: "600"
