# Generated by Django 5.1.15 on 2026-02-23 17:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Available API credits. Each row returned costs 1 unit.', max_digits=12),
        ),
    ]
