{{- if and .Values.secrets (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}-secret
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
